name: Node.js Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run tests (if any)
      - name: Run tests
        run: npm test || echo "No tests found, skipping"

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t node-app .

      # 6️⃣ Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sanjaypallapu11
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 7️⃣ Tag and push image
      - name: Push Docker image
        run: |
          docker tag node-app sanjaypallapu11/node-app:latest
          docker push sanjaypallapu11/node-app:latest

